# ----------------------------------------------------------------------------G
# Name     : .cshrc
# Function : Users startup-file for csh and tcsh
#
# Note     : Please do not edit this file until you have read the
#            site policy file for dot-files: /etc/home/README.*
#
# ----------------------------------------------------------------------------
if (-r /etc/home/cshrc && -d /env) then
   source /etc/home/cshrc
else
   source .cshrc.old
endif

# ccstart_gsn ndpgsn_5_0 <view>
alias crel 'ccstart_gsn ndpgsn_5_0 epetorp__ndpgsn_5_0_rel'
alias ctest 'ccstart_gsn ndpgsn_5_0 epetorp__ndpgsn_5_0_wb__ndpgsn_5_0_epetorp_make_ss7test'
alias cnocc 'ccstart_gsn ndpgsn_5_0 epetorp__ndpgsn_5_0_wb__ndpgsn_5_0_nocc_build'
alias cnocco 'ccstart_gsn ndpgsn_5_0 epetorp__ndpgsn_5_0_wb__ndpgsn_5_0_nocc_build_orig'

alias ccref 'ccstart_gsn ndpgsn_5_0 epetorp__ndpgsn_5_0_wb__cxs101289_llvptb_104_r1a12_130926182238'



alias coi 'ct lsco -cview -short -avobs'
alias sx 'ssh -2 -X'


alias cdb 'cd /vobs/gsn_autogsn/build'
alias cdp 'cd /vobs/gsn_autogsn/lib/python'

alias ccode 'cd /vobs/gsn/product/code'
alias e /usr/bin/emacs
alias e24 /app/emacs/24.3/RHEL6/bin/emacs

alias vi vim

alias gstat 'git status -uno'


alias cdw 'cd /proj/sgsn-program/work/epetorp/'
alias cds 'cd /proj/sgsn-program/work/epetorp/product/code'
alias cdg 'cd /proj/git_workspace/pdupc/epetorp'

alias prom 'set prompt = "\n[%{\033[0;31m%}%m%{\033[0;34m%}]%{\033[1;34m%}%{\033[0;34m%}[$CC_VIEW][%{\033[0;32m%}%~]\n#%{\033[0m%} "'
alias sv 'basename $CLEARCASE_ROOT'
alias cpre 'ct diff -pre -ser'
alias ctci 'ct ci'
alias ctco 'ct co'
alias ctlsc 'ct lsc'

alias btr /vobs/gsn/tools/3pp/erlang_bt_tool/bt_run
alias fl  '/vobs/gsn/tools/3pp/erlang_bt_tool/bt_fix_links -l'
alias crm 'ct rmname'
alias cln 'ct ln -s'
alias m gmake

if ! $?CLEARCASE_ROOT then
  setenv CC_VIEW ""
else 
  setenv CC_VIEW `basename $CLEARCASE_ROOT`
endif

# GIT ALIASES
alias glg 'git log --graph --pretty=format:"%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset" --abbrev-commit'
alias gst 'git status -s -b'
alias gci 'git commit -a -m'
alias gco 'git pull --rebase'

if ( -f "${HOME}"/.dir_colors ) then
    eval `/usr/bin/dircolors -c "${HOME}"/.dir_colors`
else if ( -f /etc/DIR_COLORS ) then
    eval `/usr/bin/dircolors -c /etc/DIR_COLORS`
endif

set prompt = "\n[%{\033[0;1;33m%}%m%{\033[0;1;36m%}]%{\033[1;32m%}%{\033[0;1;36m%}[$CC_VIEW][%{\033[0;1;32m%}%~]\n#%{\033[0m%} "



setenv http_proxy www-proxy:8080
setenv https_proxy www-proxy:8080

alias gws '~/gsnws/gsnws'
alias cc5 'ccstart_gsn ndpgsn_5_0'
alias cca 'ccstart_gsn autogsn'

setenv GSN_WS_PREFIX /proj/git_workspace/pdupc/epetorp
setenv GSN_WS_PACKAGES /home/epetorp/gsnws

